import { createSupabaseServerClient } from "@/lib/supabase/server";
import { saveLocation } from "@/app/admin/actions";

const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export default async function LocationsPage() {
  const supabase = await createSupabaseServerClient();
  const { data: locationRows } = await supabase.from("locations").select("id,name,phone,address,active,location_opening_hours(day_of_week,open_time,close_time,active)").order("name");
  const locations = locationRows ?? [];
  return <div><p className="text-xs uppercase tracking-[0.18em] text-gold-dark">Locations</p><h1 className="mt-2 font-serif text-4xl text-brown-900">Studios & hours</h1><div className="mt-8 space-y-5">{locations.map((location) => { const hours = new Map((location.location_opening_hours as Array<{ day_of_week: string; open_time: string; close_time: string }> | null)?.map((row) => [row.day_of_week, row]) ?? []); return <form action={saveLocation} key={location.id} className="rounded-3xl border border-sand-200 bg-cream-50 p-6 shadow-sm"><input type="hidden" name="id" value={location.id} /><div className="grid gap-4 md:grid-cols-3"><label className="text-sm">Location name<input name="name" defaultValue={location.name} required className="mt-1 w-full rounded-xl border border-sand-200 px-3 py-2" /></label><label className="text-sm">Phone<input name="phone" defaultValue={location.phone} required className="mt-1 w-full rounded-xl border border-sand-200 px-3 py-2" /></label><label className="text-sm">Address<input name="address" defaultValue={location.address || ""} className="mt-1 w-full rounded-xl border border-sand-200 px-3 py-2" /></label></div><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" name="active" defaultChecked={location.active} />Active location</label><details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-sage-700">Edit opening hours</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{days.map((day) => { const entry = hours.get(day); return <div key={day} className="rounded-xl border border-sand-100 p-3"><p className="text-xs font-medium">{day}</p><div className="mt-2 flex gap-2"><input aria-label={`${day} open`} name={`${day}_open`} type="time" defaultValue={entry ? String(entry.open_time).slice(0,5) : ""} className="min-w-0 flex-1 rounded-lg border border-sand-200 px-2 py-1 text-xs" /><input aria-label={`${day} close`} name={`${day}_close`} type="time" defaultValue={entry ? String(entry.close_time).slice(0,5) : ""} className="min-w-0 flex-1 rounded-lg border border-sand-200 px-2 py-1 text-xs" /></div></div>; })}</div></details><button className="mt-5 rounded-full bg-sage-700 px-5 py-2.5 text-sm font-medium text-cream-50">Save location</button></form>; })}</div></div>;
}
